/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/5.6.4/userguide/multi_project_builds.html
 */

rootProject.name = "Lark-Openapi"
include("lark-openapi", "lark-openapi-starter")

object Versions {
  object Plugin {
    const val dependencyManagementPluginVersion = "1.0.8.RELEASE"
    const val springBootGradlePluginVersion = "2.2.2.RELEASE"
  }
}

pluginManagement {
  resolutionStrategy {
    eachPlugin {
      if (requested.id.id == "org.springframework.boot") {
        useVersion(Versions.Plugin.springBootGradlePluginVersion)
      }

      if (requested.id.id == "io.spring.dependency-management") {
        useVersion(Versions.Plugin.dependencyManagementPluginVersion)
      }
    }
  }
}
